environment:
  matrix:
  - TOXENV: py36
  - TOXENV: py37

build: off

install:
- python -m pip install -U pip
- python -m pip install -U tox setuptools setuptools_scm
- python -m pip install .

test_script:
- tox
